import type { ContentBlock } from "./types";

const base = { introducedIn: "v3" as const, order: 0 };

export const aboutBlocks: ContentBlock[] = [
  {
    ...base,
    id: "about_h",
    type: "heading",
    level: 2,
    text: "Saathvik Kellampalli",
    anchor: "saathvik-kellampalli",
    order: 1,
  },
  {
    ...base,
    id: "about_sub",
    type: "prose",
    emphasis: "lead",
    text: "Second year, BS in Applied AI & Data Science — IIT Jodhpur",
    order: 2,
  },
  {
    ...base,
    id: "about_p1",
    type: "prose",
    text: "I build things and put them on the internet.",
    order: 3,
  },
  {
    ...base,
    id: "about_p2",
    type: "prose",
    text: "I'm two years into a BS in Applied AI & Data Science at IIT Jodhpur, and I've spent most of that time building — around two dozen projects across web apps, AI tools, mobile, and scroll-driven 3D. Some are live. Most were built to learn something. A few are in the Recycle Bin, where they belong.",
    order: 4,
  },
  {
    ...base,
    id: "about_p3",
    type: "prose",
    text: "Before college I did paid data work on Fiverr — cleaning and reformatting messy PDFs and spreadsheets for three clients through 2024. It wasn't engineering, but it was the first time someone paid me for output, and it taught me what a deadline actually is.",
    order: 5,
  },
  {
    ...base,
    id: "about_p4",
    type: "prose",
    text: "The thing I'm most pleased with is small: a feature PR merged into `langchain-ai/langchain`. Someone offered me freelance work on the condition that I could land a contribution in a repository that size. I'd never touched it. I found a real gap in the OpenRouter integration, wrote it up, fixed it, and it was merged within 24 hours. That's the first time my code was judged by people who had no reason to be kind about it.",
    order: 6,
  },
  {
    ...base,
    id: "about_disclosure",
    type: "callout",
    variant: "disclosure",
    title: "One thing you should know before you read anything else here",
    text: "I develop AI-assisted. Most of what I've shipped was built that way. I'm not hiding it, because I think the interesting question isn't whether you use the tools — it's whether you can tell when they're wrong. I'm still building that. The skills section on this site is graded on evidence, not on confidence, and you'll notice nothing on it claims I can debug anything yet. That's deliberate, and it'll change as I earn it.\n\nI'd rather you find this out here than in an interview.",
    order: 7,
  },
];

export const langchainBlocks: ContentBlock[] = [
  {
    ...base,
    id: "lc_h_problem",
    type: "heading",
    level: 2,
    text: "Problem",
    anchor: "problem",
    order: 1,
  },
  {
    ...base,
    id: "lc_p1",
    type: "prose",
    text: "The `langchain-openrouter` package dropped a field that mattered.",
    order: 2,
  },
  {
    ...base,
    id: "lc_p2",
    type: "prose",
    text: "OpenRouter is a routing layer: you ask for a model, and it picks a backend to actually serve the request. With `allow_fallbacks` enabled, the same model and the same prompt can land on different backends seconds apart — Novita on one call, DeepInfra on the next. Those backends don't always share quantisation, latency, or price.",
    order: 3,
  },
  {
    ...base,
    id: "lc_p3",
    type: "prose",
    text: "OpenRouter tells you which one served you. It returns a top-level `provider` field on every chat completion.",
    order: 4,
  },
  {
    ...base,
    id: "lc_p4",
    type: "prose",
    emphasis: "lead",
    text: "`ChatOpenRouter` threw it away.",
    order: 5,
  },
  {
    ...base,
    id: "lc_role",
    type: "heading",
    level: 2,
    text: "My role",
    anchor: "my-role",
    order: 6,
  },
  {
    ...base,
    id: "lc_role_p",
    type: "prose",
    text: "Solo. Discovery, reproduction, write-up, implementation, and the PR.",
    order: 7,
  },
  {
    ...base,
    id: "lc_role_d",
    type: "callout",
    variant: "disclosure",
    title: "And the part I won't dress up",
    text: "this was AI-assisted from end to end. I used ChatGPT and Claude Code to survey the codebase, locate the relevant call sites, and draft both the issue and the fix. I do not claim to have read `langchain-openrouter` cover to cover, and I don't claim deep LangChain expertise on the strength of one merged PR.\n\nWhat I claim is narrower and, I think, more useful: **given an unfamiliar production codebase, a cold start, and a deadline, I produced a change that survived maintainer review and shipped.**",
    order: 8,
  },
  {
    ...base,
    id: "lc_goals",
    type: "heading",
    level: 2,
    text: "Goals and constraints",
    anchor: "goals-and-constraints",
    order: 9,
  },
  {
    ...base,
    id: "lc_kv",
    type: "keyValue",
    title: "Goals and constraints",
    rows: [
      { key: "Goal", value: "One merged, non-trivial contribution" },
      { key: "Hard constraint", value: "Days, not weeks — a client was waiting" },
      { key: "Hard constraint", value: "Zero prior knowledge of the codebase" },
      {
        key: "Hard constraint",
        value:
          "Strictly backwards compatible. A behaviour change in a widely-used integration is a rejection.",
      },
      { key: "Self-imposed", value: "Reproducible against the live API, not theorised from source" },
      { key: "Out of scope", value: "Refactoring, adjacent bugs, anything enlarging the diff" },
    ],
    order: 10,
  },
  {
    ...base,
    id: "lc_code",
    type: "code",
    language: "python",
    filename: "_create_chat_result (illustration of the guard)",
    highlightLines: [1, 4],
    code: `serving_provider = response.get("provider")
...
if serving_provider:
    message.response_metadata["provider"] = serving_provider`,
    order: 11,
  },
  {
    ...base,
    id: "lc_cmp",
    type: "comparison",
    title: "Alternatives I ruled out, and said so in the issue",
    columns: ["Option", "Why not"],
    rows: [
      [
        "`ChatOpenAI` with OpenRouter's `base_url` *(what I was using)*",
        'Drops `provider` too, and misreports `ls_provider` as `"openai"`',
      ],
      [
        "Pin one backend, disable fallbacks",
        "You gain provenance by giving up the routing availability that's the reason to use OpenRouter",
      ],
      [
        "Follow-up `GET /api/v1/generation?id=` per call",
        "Works — it's how I identified the backends above — but it's an extra round trip and arrives too late to attach to the run",
      ],
      [
        "Local subclass overriding `_create_chat_result`",
        "Three lines against a private method, rewritten by every user who needs provenance",
      ],
    ],
    order: 12,
  },
  {
    ...base,
    id: "lc_quote",
    type: "quote",
    text: "I'd rather you find this out here than in an interview.",
    attribution: "About Me — same honesty stance, earlier in the document",
    order: 13,
  },
  {
    ...base,
    id: "lc_limit",
    type: "callout",
    variant: "limitation",
    title: "Limitation",
    text: "This was the first time my code was judged by people with no reason to be generous about it, and it held up. It also showed me the shape of my own gap. I could find the problem, reproduce it, and argue for the fix — but I was leaning on tooling to navigate a codebase I couldn't have navigated alone. That is a real limitation and it's the thing I'm working on now.",
    order: 14,
  },
  {
    ...base,
    id: "lc_note",
    type: "callout",
    variant: "note",
    text: "The write-up carries the change. The diff was small enough that a maintainer could have written it faster than reading my issue.",
    order: 15,
  },
  {
    ...base,
    id: "lc_caution",
    type: "callout",
    variant: "caution",
    text: "Publication is conditional on being able to explain the change unaided. If it cannot be answered from memory, this case study must not ship.",
    order: 16,
  },
  {
    ...base,
    id: "lc_list",
    type: "list",
    style: "bullet",
    items: [
      "What `AIMessage.response_metadata` is and who consumes it",
      "Why `_create_chat_result` and the two streaming paths are separate code paths",
      "Why the truthy guard preserves backwards compatibility",
      "Why `provider` and `model_provider` are different things",
      "What `allow_fallbacks` does and why it makes provenance necessary",
    ],
    order: 17,
  },
  {
    ...base,
    id: "lc_img",
    type: "image",
    asset: {
      id: "a3_1",
      alt: "The merged PR page for langchain-ai/langchain #39301 — proof, not decoration",
    },
    size: "full",
    order: 18,
  },
  {
    ...base,
    id: "lc_gal",
    type: "gallery",
    assets: [
      { id: "g1", alt: "Gallery screenshot placeholder one" },
      { id: "g2", alt: "Gallery screenshot placeholder two" },
    ],
    caption: "No screenshots exist yet. Layout must hold with empty wells.",
    order: 19,
  },
  {
    ...base,
    id: "lc_diag",
    type: "diagram",
    format: "mermaid",
    altDescription:
      "Request to OpenRouter to backend to response, then three construction paths, then the drop point of the provider field.",
    order: 20,
  },
  {
    ...base,
    id: "lc_metrics",
    type: "metrics",
    metrics: [],
    order: 21,
  },
  {
    ...base,
    id: "lc_links",
    type: "linkGroup",
    title: "Links",
    links: [
      {
        kind: "pr",
        label: "PR #39301",
        url: "https://github.com/langchain-ai/langchain/pull/39301",
        verified: false,
      },
      {
        kind: "issue",
        label: "Issue #39298",
        url: "https://github.com/langchain-ai/langchain/issues/39298",
        verified: false,
      },
    ],
    order: 22,
  },
  {
    ...base,
    id: "lc_div",
    type: "divider",
    order: 23,
  },
  {
    ...base,
    id: "lc_embed",
    type: "embed",
    provider: "other",
    url: "https://example.invalid",
    title: "No embed in V1 case study — empty slot for completeness",
    order: 24,
  },
];
